/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dharma.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PMMessage service. Represents a row in the &quot;private_message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dharma.model.impl.PMMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dharma.model.impl.PMMessageImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a p m message model instance should use the {@link PMMessage} interface instead.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PMMessage
 * @see com.dharma.model.impl.PMMessageImpl
 * @see com.dharma.model.impl.PMMessageModelImpl
 * @generated
 */
public interface PMMessageModel extends BaseModel<PMMessage> {
	/**
	 * Gets the primary key of this p m message.
	 *
	 * @return the primary key of this p m message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this p m message
	 *
	 * @param pk the primary key of this p m message
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the message id of this p m message.
	 *
	 * @return the message id of this p m message
	 */
	public long getMessageId();

	/**
	 * Sets the message id of this p m message.
	 *
	 * @param messageId the message id of this p m message
	 */
	public void setMessageId(long messageId);

	/**
	 * Gets the subject of this p m message.
	 *
	 * @return the subject of this p m message
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this p m message.
	 *
	 * @param subject the subject of this p m message
	 */
	public void setSubject(String subject);

	/**
	 * Gets the body of this p m message.
	 *
	 * @return the body of this p m message
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this p m message.
	 *
	 * @param body the body of this p m message
	 */
	public void setBody(String body);

	/**
	 * Gets the parent message id of this p m message.
	 *
	 * @return the parent message id of this p m message
	 */
	public long getParentMessageId();

	/**
	 * Sets the parent message id of this p m message.
	 *
	 * @param parentMessageId the parent message id of this p m message
	 */
	public void setParentMessageId(long parentMessageId);

	/**
	 * Gets the owner id of this p m message.
	 *
	 * @return the owner id of this p m message
	 */
	public long getOwnerId();

	/**
	 * Sets the owner id of this p m message.
	 *
	 * @param ownerId the owner id of this p m message
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Gets the owner name of this p m message.
	 *
	 * @return the owner name of this p m message
	 */
	@AutoEscape
	public String getOwnerName();

	/**
	 * Sets the owner name of this p m message.
	 *
	 * @param ownerName the owner name of this p m message
	 */
	public void setOwnerName(String ownerName);

	/**
	 * Gets the posted date of this p m message.
	 *
	 * @return the posted date of this p m message
	 */
	public Date getPostedDate();

	/**
	 * Sets the posted date of this p m message.
	 *
	 * @param postedDate the posted date of this p m message
	 */
	public void setPostedDate(Date postedDate);

	/**
	 * Gets the recepients of this p m message.
	 *
	 * @return the recepients of this p m message
	 */
	@AutoEscape
	public String getRecepients();

	/**
	 * Sets the recepients of this p m message.
	 *
	 * @param recepients the recepients of this p m message
	 */
	public void setRecepients(String recepients);

	/**
	 * Gets a copy of this p m message as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public PMMessage toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PMMessage pmMessage);

	public int hashCode();

	public String toString();

	public String toXmlString();
}