/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dharma.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PMReadMessage service. Represents a row in the &quot;read_message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dharma.model.impl.PMReadMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dharma.model.impl.PMReadMessageImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a p m read message model instance should use the {@link PMReadMessage} interface instead.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PMReadMessage
 * @see com.dharma.model.impl.PMReadMessageImpl
 * @see com.dharma.model.impl.PMReadMessageModelImpl
 * @generated
 */
public interface PMReadMessageModel extends BaseModel<PMReadMessage> {
	/**
	 * Gets the primary key of this p m read message.
	 *
	 * @return the primary key of this p m read message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this p m read message
	 *
	 * @param pk the primary key of this p m read message
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the read message id of this p m read message.
	 *
	 * @return the read message id of this p m read message
	 */
	public long getReadMessageId();

	/**
	 * Sets the read message id of this p m read message.
	 *
	 * @param readMessageId the read message id of this p m read message
	 */
	public void setReadMessageId(long readMessageId);

	/**
	 * Gets the message id of this p m read message.
	 *
	 * @return the message id of this p m read message
	 */
	public long getMessageId();

	/**
	 * Sets the message id of this p m read message.
	 *
	 * @param messageId the message id of this p m read message
	 */
	public void setMessageId(long messageId);

	/**
	 * Gets the read date of this p m read message.
	 *
	 * @return the read date of this p m read message
	 */
	public Date getReadDate();

	/**
	 * Sets the read date of this p m read message.
	 *
	 * @param readDate the read date of this p m read message
	 */
	public void setReadDate(Date readDate);

	/**
	 * Gets a copy of this p m read message as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public PMReadMessage toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PMReadMessage pmReadMessage);

	public int hashCode();

	public String toString();

	public String toXmlString();
}