/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dharma.model.impl;

import com.dharma.model.PMBlockedUser;
import com.dharma.model.PMBlockedUserModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the PMBlockedUser service. Represents a row in the &quot;blocked_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dharma.model.PMBlockedUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PMBlockedUserImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a p m blocked user model instance should use the {@link com.dharma.model.PMBlockedUser} interface instead.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PMBlockedUserImpl
 * @see com.dharma.model.PMBlockedUser
 * @see com.dharma.model.PMBlockedUserModel
 * @generated
 */
public class PMBlockedUserModelImpl extends BaseModelImpl<PMBlockedUser>
	implements PMBlockedUserModel {
	public static final String TABLE_NAME = "blocked_user";
	public static final Object[][] TABLE_COLUMNS = {
			{ "blockedUserId", new Integer(Types.BIGINT) },
			{ "ownerId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "blockedDate", new Integer(Types.TIMESTAMP) }
		};
	public static final String TABLE_SQL_CREATE = "create table blocked_user (blockedUserId LONG not null primary key,ownerId LONG,userId LONG,blockedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table blocked_user";
	public static final String ORDER_BY_JPQL = " ORDER BY pmBlockedUser.blockedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY blocked_user.blockedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.dharma.model.PMBlockedUser"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.dharma.model.PMBlockedUser"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.dharma.model.PMBlockedUser"));

	public PMBlockedUserModelImpl() {
	}

	public long getPrimaryKey() {
		return _blockedUserId;
	}

	public void setPrimaryKey(long pk) {
		setBlockedUserId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_blockedUserId);
	}

	public long getBlockedUserId() {
		return _blockedUserId;
	}

	public void setBlockedUserId(long blockedUserId) {
		_blockedUserId = blockedUserId;
	}

	public String getBlockedUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getBlockedUserId(), "uuid",
			_blockedUserUuid);
	}

	public void setBlockedUserUuid(String blockedUserUuid) {
		_blockedUserUuid = blockedUserUuid;
	}

	public long getOwnerId() {
		return _ownerId;
	}

	public void setOwnerId(long ownerId) {
		_ownerId = ownerId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getBlockedDate() {
		return _blockedDate;
	}

	public void setBlockedDate(Date blockedDate) {
		_blockedDate = blockedDate;
	}

	public PMBlockedUser toEscapedModel() {
		if (isEscapedModel()) {
			return (PMBlockedUser)this;
		}
		else {
			return (PMBlockedUser)Proxy.newProxyInstance(PMBlockedUser.class.getClassLoader(),
				new Class[] { PMBlockedUser.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					PMBlockedUser.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		PMBlockedUserImpl clone = new PMBlockedUserImpl();

		clone.setBlockedUserId(getBlockedUserId());
		clone.setOwnerId(getOwnerId());
		clone.setUserId(getUserId());
		clone.setBlockedDate(getBlockedDate());

		return clone;
	}

	public int compareTo(PMBlockedUser pmBlockedUser) {
		int value = 0;

		value = DateUtil.compareTo(getBlockedDate(),
				pmBlockedUser.getBlockedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PMBlockedUser pmBlockedUser = null;

		try {
			pmBlockedUser = (PMBlockedUser)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = pmBlockedUser.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{blockedUserId=");
		sb.append(getBlockedUserId());
		sb.append(", ownerId=");
		sb.append(getOwnerId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", blockedDate=");
		sb.append(getBlockedDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.dharma.model.PMBlockedUser");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>blockedUserId</column-name><column-value><![CDATA[");
		sb.append(getBlockedUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ownerId</column-name><column-value><![CDATA[");
		sb.append(getOwnerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>blockedDate</column-name><column-value><![CDATA[");
		sb.append(getBlockedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _blockedUserId;
	private String _blockedUserUuid;
	private long _ownerId;
	private long _userId;
	private String _userUuid;
	private Date _blockedDate;
	private transient ExpandoBridge _expandoBridge;
}