/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dharma.model.impl;

import com.dharma.model.PMReadMessage;
import com.dharma.model.PMReadMessageModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the PMReadMessage service. Represents a row in the &quot;read_message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.dharma.model.PMReadMessageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PMReadMessageImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a p m read message model instance should use the {@link com.dharma.model.PMReadMessage} interface instead.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PMReadMessageImpl
 * @see com.dharma.model.PMReadMessage
 * @see com.dharma.model.PMReadMessageModel
 * @generated
 */
public class PMReadMessageModelImpl extends BaseModelImpl<PMReadMessage>
	implements PMReadMessageModel {
	public static final String TABLE_NAME = "read_message";
	public static final Object[][] TABLE_COLUMNS = {
			{ "readMessageId", new Integer(Types.BIGINT) },
			{ "messageId", new Integer(Types.BIGINT) },
			{ "readDate", new Integer(Types.TIMESTAMP) }
		};
	public static final String TABLE_SQL_CREATE = "create table read_message (readMessageId LONG not null primary key,messageId LONG,readDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table read_message";
	public static final String ORDER_BY_JPQL = " ORDER BY pmReadMessage.readDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY read_message.readDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.dharma.model.PMReadMessage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.dharma.model.PMReadMessage"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.dharma.model.PMReadMessage"));

	public PMReadMessageModelImpl() {
	}

	public long getPrimaryKey() {
		return _readMessageId;
	}

	public void setPrimaryKey(long pk) {
		setReadMessageId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_readMessageId);
	}

	public long getReadMessageId() {
		return _readMessageId;
	}

	public void setReadMessageId(long readMessageId) {
		_readMessageId = readMessageId;
	}

	public long getMessageId() {
		return _messageId;
	}

	public void setMessageId(long messageId) {
		_messageId = messageId;
	}

	public Date getReadDate() {
		return _readDate;
	}

	public void setReadDate(Date readDate) {
		_readDate = readDate;
	}

	public PMReadMessage toEscapedModel() {
		if (isEscapedModel()) {
			return (PMReadMessage)this;
		}
		else {
			return (PMReadMessage)Proxy.newProxyInstance(PMReadMessage.class.getClassLoader(),
				new Class[] { PMReadMessage.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					PMReadMessage.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		PMReadMessageImpl clone = new PMReadMessageImpl();

		clone.setReadMessageId(getReadMessageId());
		clone.setMessageId(getMessageId());
		clone.setReadDate(getReadDate());

		return clone;
	}

	public int compareTo(PMReadMessage pmReadMessage) {
		int value = 0;

		value = DateUtil.compareTo(getReadDate(), pmReadMessage.getReadDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PMReadMessage pmReadMessage = null;

		try {
			pmReadMessage = (PMReadMessage)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = pmReadMessage.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{readMessageId=");
		sb.append(getReadMessageId());
		sb.append(", messageId=");
		sb.append(getMessageId());
		sb.append(", readDate=");
		sb.append(getReadDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.dharma.model.PMReadMessage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>readMessageId</column-name><column-value><![CDATA[");
		sb.append(getReadMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageId</column-name><column-value><![CDATA[");
		sb.append(getMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>readDate</column-name><column-value><![CDATA[");
		sb.append(getReadDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _readMessageId;
	private long _messageId;
	private Date _readDate;
	private transient ExpandoBridge _expandoBridge;
}